function varargout=sym_oscillators_25(action,varargin)
%% Automatically generated with matlabFunction
% 
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'ntau'
   varargout{1}=2;
   return
  case 'npar'
   varargout{1}=5;
   return
  case 'nf'
   varargout{1}=4;
   return
  case 'nx'
   varargout{1}=4;
   return
  case 'tp_del'
   varargout{1}=0;
   return
  case 'maxorder'
   varargout{1}=2;
   return
  case 'iscollected'
   varargout{1}=0;
   return
  case 'directional_derivative'
   varargout{1}=1;
   return
  case 'sys_tau_seq'
   varargout{1}={};
   return
  case 'sys_tau_in'
   varargout{1}=[];
   return
  case 'xpattern'
   varargout{1}=[1  1  2  1  3  1  4  1  1  2  2  2  3  2  4  2  1  3  2  3  3  3  4  3];
   return
end
ind=varargin{1};
order=varargin{2};
nout=varargin{3};
f=str2func(sprintf('sym_oscillators_25_%s_%d_%d',action,ind,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{4:end});
end



function [out_1,out_2,out_3,out_4] = sym_oscillators_25_rhs_1_0(in1,in2,in3,in4)
%SYM_OSCILLATORS_25_RHS_1_0
%    [OUT_1,OUT_2,OUT_3,OUT_4] = SYM_OSCILLATORS_25_RHS_1_0(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    17-Jan-2025 10:24:12

in_1_n1 = in1(:,1);
in_1_n2 = in1(:,2);
in_1_n3 = in1(:,3);
in_1_n4 = in1(:,4);
in_1_n5 = in1(:,5);
in_1_n6 = in1(:,6);
in_1_n7 = in1(:,7);
in_1_n8 = in1(:,8);
in_1_n9 = in1(:,9);
in_2_n1 = in2(:,1);
in_2_n2 = in2(:,2);
in_2_n3 = in2(:,3);
in_1_n10 = in1(:,10);
in_1_n11 = in1(:,11);
in_1_n12 = in1(:,12);
t2 = -in_1_n10;
t3 = -in_1_n11;
t4 = -in_1_n12;
t5 = in_1_n9+t2;
t6 = in_1_n9+t3;
t7 = in_1_n9+t4;
t8 = in_1_n10+t3;
t9 = in_1_n10+t4;
t10 = in_1_n11+t4;
t11 = in_2_n2.*t5;
t12 = in_2_n2.*t6;
t13 = in_2_n2.*t7;
out_1 = in_2_n3-t11-t12-t13-in_1_n5.*in_2_n1-in_1_n1.^3;
if nargout > 1
    t14 = in_2_n2.*t8;
    t15 = in_2_n2.*t9;
    out_2 = in_2_n3+t11-t14-t15-in_1_n6.*in_2_n1-in_1_n2.^3;
end
if nargout > 2
    t16 = in_2_n2.*t10;
    out_3 = in_2_n3+t12+t14-t16-in_1_n7.*in_2_n1-in_1_n3.^3;
end
if nargout > 3
    out_4 = in_2_n3+t13+t15+t16-in_1_n8.*in_2_n1-in_1_n4.^3;
end
end


function [out_1,out_2,out_3,out_4] = sym_oscillators_25_rhs_1_1(in1,in2,in3,in4)
%SYM_OSCILLATORS_25_RHS_1_1
%    [OUT_1,OUT_2,OUT_3,OUT_4] = SYM_OSCILLATORS_25_RHS_1_1(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    17-Jan-2025 10:24:12

in_1_n1 = in1(:,1);
in_1_n2 = in1(:,2);
in_1_n3 = in1(:,3);
in_1_n4 = in1(:,4);
in_1_n5 = in1(:,5);
in_1_n6 = in1(:,6);
in_1_n7 = in1(:,7);
in_1_n8 = in1(:,8);
in_1_n9 = in1(:,9);
in_2_n1 = in2(:,1);
in_2_n2 = in2(:,2);
in_3_n1 = in3(:,1);
in_3_n2 = in3(:,2);
in_3_n3 = in3(:,3);
in_3_n4 = in3(:,4);
in_3_n5 = in3(:,5);
in_3_n6 = in3(:,6);
in_3_n7 = in3(:,7);
in_3_n8 = in3(:,8);
in_3_n9 = in3(:,9);
in_4_n1 = in4(:,1);
in_4_n2 = in4(:,2);
in_4_n3 = in4(:,3);
in_1_n10 = in1(:,10);
in_1_n11 = in1(:,11);
in_1_n12 = in1(:,12);
in_3_n10 = in3(:,10);
in_3_n11 = in3(:,11);
in_3_n12 = in3(:,12);
t2 = -in_1_n10;
t3 = -in_1_n11;
t4 = -in_1_n12;
t5 = -in_3_n10;
t6 = -in_3_n11;
t7 = -in_3_n12;
t8 = in_1_n9+t2;
t9 = in_1_n9+t3;
t10 = in_1_n9+t4;
t11 = in_1_n10+t3;
t12 = in_1_n10+t4;
t13 = in_1_n11+t4;
t14 = in_3_n9+t5;
t15 = in_3_n9+t6;
t16 = in_3_n9+t7;
t17 = in_3_n10+t6;
t18 = in_3_n10+t7;
t19 = in_3_n11+t7;
t20 = in_4_n2.*t8;
t21 = in_4_n2.*t9;
t22 = in_4_n2.*t10;
t23 = in_4_n2.*t11;
t24 = in_4_n2.*t12;
t25 = in_4_n2.*t13;
t26 = in_2_n2.*t14;
t27 = in_2_n2.*t15;
t28 = in_2_n2.*t16;
out_1 = in_4_n3-t20-t21-t22-t26-t27-t28-in_1_n5.*in_4_n1-in_2_n1.*in_3_n5-in_1_n1.^2.*in_3_n1.*3.0;
if nargout > 1
    t29 = in_2_n2.*t17;
    t30 = in_2_n2.*t18;
    out_2 = in_4_n3+t20-t23-t24+t26-t29-t30-in_1_n6.*in_4_n1-in_2_n1.*in_3_n6-in_1_n2.^2.*in_3_n2.*3.0;
end
if nargout > 2
    t31 = in_2_n2.*t19;
    out_3 = in_4_n3+t21+t23-t25+t27+t29-t31-in_1_n7.*in_4_n1-in_2_n1.*in_3_n7-in_1_n3.^2.*in_3_n3.*3.0;
end
if nargout > 3
    out_4 = in_4_n3+t22+t24+t25+t28+t30+t31-in_1_n8.*in_4_n1-in_2_n1.*in_3_n8-in_1_n4.^2.*in_3_n4.*3.0;
end
end


function [out_1,out_2,out_3,out_4] = sym_oscillators_25_rhs_1_2(in1,in2,in3,in4)
%SYM_OSCILLATORS_25_RHS_1_2
%    [OUT_1,OUT_2,OUT_3,OUT_4] = SYM_OSCILLATORS_25_RHS_1_2(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    17-Jan-2025 10:24:13

in_1_n1 = in1(:,1);
in_1_n2 = in1(:,2);
in_1_n3 = in1(:,3);
in_1_n4 = in1(:,4);
in_3_n1 = in3(:,1);
in_3_n2 = in3(:,2);
in_3_n3 = in3(:,3);
in_3_n4 = in3(:,4);
in_3_n5 = in3(:,5);
in_3_n6 = in3(:,6);
in_3_n7 = in3(:,7);
in_3_n8 = in3(:,8);
in_3_n9 = in3(:,9);
in_4_n1 = in4(:,1);
in_4_n2 = in4(:,2);
in_3_n10 = in3(:,10);
in_3_n11 = in3(:,11);
in_3_n12 = in3(:,12);
t2 = -in_3_n10;
t3 = -in_3_n11;
t4 = -in_3_n12;
t5 = in_3_n9+t2;
t6 = in_3_n9+t3;
t7 = in_3_n9+t4;
t8 = in_3_n10+t3;
t9 = in_3_n10+t4;
t10 = in_3_n11+t4;
t11 = in_4_n2.*t5.*2.0;
t12 = in_4_n2.*t6.*2.0;
t13 = in_4_n2.*t7.*2.0;
out_1 = -t11-t12-t13-in_3_n5.*in_4_n1.*2.0-in_1_n1.*in_3_n1.^2.*6.0;
if nargout > 1
    t14 = in_4_n2.*t8.*2.0;
    t15 = in_4_n2.*t9.*2.0;
    out_2 = t11-t14-t15-in_3_n6.*in_4_n1.*2.0-in_1_n2.*in_3_n2.^2.*6.0;
end
if nargout > 2
    t16 = in_4_n2.*t10.*2.0;
    out_3 = t12+t14-t16-in_3_n7.*in_4_n1.*2.0-in_1_n3.*in_3_n3.^2.*6.0;
end
if nargout > 3
    out_4 = t13+t15+t16-in_3_n8.*in_4_n1.*2.0-in_1_n4.*in_3_n4.^2.*6.0;
end
end

